In [47]:
#matrix multiplication
import numpy as num
a=num.array(([1,2,3],[3,4,5],[5,6,7]))
b=num.array(([3,4,5],[4,3,2],[5,6,4]))
print("\nmatix 1:\n")
print("\n------------------\n")
print(a)
print("\nmatrix 2\n")
print("\n------------------\n")
print(b)
print("\nmatrix1 * matrix 2\n")
print("\n------------------\n")
c=num.dot(a,b)
print(c)
print(" \ntranspose\n")
print("\n------------------\n")
d=num.transpose(c)
print(d)


matix 1:


------------------

[[1 2 3]
 [3 4 5]
 [5 6 7]]

matrix 2


------------------

[[3 4 5]
 [4 3 2]
 [5 6 4]]

matrix1 * matrix 2


------------------

[[26 28 21]
 [50 54 43]
 [74 80 65]]
 
transpose


------------------

[[26 50 74]
 [28 54 80]
 [21 43 65]]


In [24]:
import numpy as num
a=num.array([1,2,3,4,5,6,7,8,9])
c=num.array([1,5,4,3,2,7,6,8,7])
b=a.reshape(3,3)
d=c.reshape(3,3)
print(b)
print(d)
e=num.dot(b,d)
print(e)
f=num.transpose(e)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 5 4]
 [3 2 7]
 [6 8 7]]
[[ 25  33  39]
 [ 55  78  93]
 [ 85 123 147]]
[[ 25  55  85]
 [ 33  78 123]
 [ 39  93 147]]


In [26]:
a=num.arange(9)

print(a)

[0 1 2 3 4 5 6 7 8]


In [30]:
#zero matrix
a=num.zeros(([2,2]),dtype='i')
print(a)

[[0 0]
 [0 0]]


In [49]:
#reshape and back to origin
a=num.array([1,2,3,4,4,5,6,7,7])
print("\n reshape into matrix form\n")
print("\n------------------\n")
b=a.reshape(3,3)
print(b)
print("\n the matrix into its initial form\n")
print("\n------------------\n")
c=b.ravel()
print(c)


 reshape into matrix form


------------------

[[1 2 3]
 [4 4 5]
 [6 7 7]]

 the matrix into its initial form


------------------

[1 2 3 4 4 5 6 7 7]


In [50]:
#program to find svd
from scipy.linalg import svd
v,s,t=svd(b)
print("\n matrix into svd \n")
print("\n------------------\n")
print(v)
print(s)
print(t)
print("\n svd form into initial \n")
print("\n------------------\n")
r=(v@num.diag(s)@t)
print(r)


 matrix into svd 


------------------

[[-0.25094612  0.93763527  0.24055384]
 [-0.5283942   0.07553223 -0.84563257]
 [-0.81106449 -0.33931547  0.47648652]]
[14.26059272  1.15661527  0.54565233]
[[-0.50705535 -0.58152706 -0.63617698]
 [-0.68832621 -0.17102385  0.70495239]
 [-0.51875033  0.79534717 -0.31356175]]

 svd form into initial 


------------------

[[1. 2. 3.]
 [4. 4. 5.]
 [6. 7. 7.]]


In [53]:
#matrix multiplication
import numpy as num
a=num.array(([1,2,3],[3,4,5],[5,6,7]))


print("\nmatrix \n")
print("\n------------------\n")
print(a)
print("\n slicing with position 1st to last row and 2nd column to last\n")
print("\n------------------\n")
print(a[0:,1:])


matrix 


------------------

[[1 2 3]
 [3 4 5]
 [5 6 7]]

 slicing with position 1st to last row and 2nd column to last


------------------

[[2 3]
 [4 5]
 [6 7]]
