In [2]:
#matrix multiplication
import numpy as num

b=num.array(([3,4,5],[4,3,2],[5,6,4]))

print("\nmatrix \n")
print("\n------------------\n")
print(b)



matrix 


------------------

[[3 4 5]
 [4 3 2]
 [5 6 4]]


In [3]:
#program to find svd
from scipy.linalg import svd
v,s,t=svd(b)
print("\n matrix into svd \n")
print("\n------------------\n")
print(v)
print(s)
print(t)
print("\n svd form into initial \n")
print("\n------------------\n")
r=(v@num.diag(s)@t)
print(r)


 matrix into svd 


------------------

[[-0.55955562  0.776486   -0.2897706 ]
 [-0.42479589 -0.56891112 -0.70419357]
 [-0.71165017 -0.27094211  0.64818548]]
[12.28204518  2.12179083  0.80583483]
[[-0.56473504 -0.63364945 -0.5287369 ]
 [-0.61311277 -0.10672214  0.78275355]
 [-0.55241928  0.7662237  -0.32822884]]

 svd form into initial 


------------------

[[3. 4. 5.]
 [4. 3. 2.]
 [5. 6. 4.]]
